name: CI-CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .Net Core 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1'
      
      - name: Restore Dependacies
        run: dotnet Restore

      - name: build App
        run: dotnet build -c Release 

      - name: Run Automation Tests
        run: dotnet test -c Release --no-build

      - name: Deploy To IIS
        run: |
            C:\Windows\System32\iisreset.exe /stop
            xcopy /s /y .\myapp\* C:\PUBLISH\Platinum
            C:\Windows\System32\iisreset.exe /star

